name: AutoReboot
author: WhatClick
website: https://github.com/WhatClick/AutoReboot

version: 0.0.1
main: AutoReboot\Main
api: 5.28.1

commands:
  setreboottime:
    description: Set the automatic reboot time interval
    usage: /setreboottime <time in seconds>
    permission: autoreboot.command.setreboottime
    permission-message: You do not have permission to use this command.
